plugins:
  - jekyll-feed
  - jekyll-sitemap

author: obrhubr
url: https://obrhubr.org

kramdown:
  math_engine: katex

feed:
  excerpt_only: true
  referrer: "?ref=rss"

plugins_dir: ./_plugins

exclude:
  - scripts
  - .github
  - CNAME
  - README.md